title: "Biological Evolution Across Scales: Mathematical modelling and statistical inference"
description: >-
  EPFL, April 16–21, 2023
logo: images/logo.png

address: Swiss Federal Institute of Technology Lausanne (EPFL), Rte Cantonale, 1015 Lausanne, Switzerland
email: bevas@epfl.ch

socials:
  Twitter: "#"
  GitHub: "#"
