title: "Biological Evolution Across Scales: Mathematical modelling and statistical inference"
description: >
  Bernoulli Center, EPFL<br />
  April 17–21, 2023
logo: images/logo.svg

address: Swiss Federal Institute of Technology Lausanne (EPFL), Rte Cantonale, 1015 Lausanne, Switzerland
email: bevas@epfl.ch

socials:
  Slack: "#"
